### ISSUE TITLE
[Feature] - Support for layout files

### ISSUE THREAD

**Issue by Jarrodsz** [Thomascogez/nodemailer-mjml#11]
Great plugin! 

I was planning to build this myself until I came across your npm package.
There is just 1 small things Im missing.

Would it be possible to support layouts?

Layouts would be just a wrapper miml file with certain content where other mail templates could place there content in.

```
app/mailers/layouts/onboard.mjml
app/mailers/welcome.mjml
```

Layouts would reside in a specific layouts folder and then to be use like to:

```
export const resetPasswordEmail = async () => {
  const url = process.env.REMIX_URL_APP?.toString();
  // get user from email
  //const userName = user.firstName + " " + user.lastName
  await transport.sendMail({
    layout: "onboard",
    templateName: "reset-password",
    templateData: {
      ...
    }
  });
};
```

This way you have the flexibility to have certain layouts and elements in a email and not having to duplicate this true all of the mjml pages!

**Comment by Jarrodsz** [comment]
I have the suggested setup in my rails application which uses a main layout like so:

```
<mjml>

  <mj-head>
    <mj-preview></mj-preview>
    <%= render partial: "mailers/shared/head" %>
  </mj-head>

  <mj-body background-color="#F2F2F2">

    <mj-section>
      <mj-column>
        <%= render partial: "mailers/shared/header" %>
      </mj-column>
    </mj-section>

    <%= yield %>

    <mj-section>
        <mj-column>
            <%= render partial: "mailers/shared/footer" %>
        </mj-column>
    </mj-section>

  </mj-body>

</mjml>
``` 

This way you could even split the footer in a separate file, just for easy maintenance or conditional logic ( separate footer on separate emails ). It just gives a lot more flexibility.

The YIELD part would be where my current implementation inserts the content of a specific mail file like /mailers/welcome.mjml

**Comment by Thomascogez** [comment]
Did layout should support only one slot  ? I was thinking about somehing like this: 

What do you think about

```mjml
// file main-content.mjml
<mj-section>
  <mj-column>
    <mj-text>Hello {{userName}}</mj-text>
  </mj-column>
</mj-section>

// file footer.mjml
<mj-section>
  <mj-column>
    <mj-text>footer</mj-text>
  </mj-column>
</mj-section>

// file onboard.mjml
<mjml>
  <mj-head>
    <mj-preview></mj-preview>
  </mj-head>

  <mj-body background-color="#F2F2F2">

    <mj-section>
      <mj-column>
        {{slot:content}}
      </mj-column>
    </mj-section>
    <mj-section>
        <mj-column>
         {{slot:footer}}
        </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

```ts
 await transport.sendMail({
    layout: "onboard",
    templateData: {
      userName: "John doe"
      ...
    }
   templateLayoutSlots: {
     content: "main-content",
     footer: "footer"
    }
});
```
and when the templates are compiled `{{slot:footer}}, {{slot:content}}` will be replaced with `<mj-include path="template/xxx" />`

**Comment by Jarrodsz** [comment]
That would be even better!
Perhaps it would be nice, if there would be some defaults - so you do not have to expliciet set each property.

Say for example 
```
 templateLayoutSlots: {
     content: "main-content",
    }
```

When footer does not exists it loads the footer.mjml from a /mailer/templates/layout/footer.mjml 

Then you have basic Ruby on Rails mjml rails mailer implementation on node (Y)

**Comment by Thomascogez** [comment]
I was thinking that slot:name could be dynamic like that you can define any slots you want in the layout file

**Comment by Thomascogez** [comment]
Like having two behavior:
- Using templateName and everything is rendered like it is today
- Using Layout and and slots and templateName is omitted 

Tell me if it is coherent to you ?

**Comment by Jarrodsz** [comment]
Yes that seems like a really nice solution.
But, with the option to not specify something like footer - then it would default to a default footer.

I think that would handle all situations for a flexible mail template buildup.

**Comment by Thomascogez** [comment]
By that you mean for example declaring a footer slot in you layout and not giving the key in templateLayoutSlots ?

How  "default footer" should be determined ?

**Comment by Jarrodsz** [comment]
That's a good one perhaps there is no footer. 
How about this:

footer *not specified  ( no slot property for footer) then footer defaults to a default one /mailers/shared/footer.mjml
footer = false renders no footer
footer *specified then footer would load the footer specified, if they where to be stored in a /mailer/shared/footer one would just include this mjml part as footer.

Would that handle all cases?

**Comment by Thomascogez** [comment]
Sound good !  I will start working on this feature this week-end, I keep this issue open until a new release if you have any extra suggestions / recommandations

**Comment by Jarrodsz** [comment]
Great! Interested to see how you add it relative new to the node stack.

**Comment by Thomascogez** [comment]
Hey you can see the progress here https://github.com/Thomascogez/nodemailer-mjml/pull/13

**Comment by Jarrodsz** [comment]
Looks great as far as I can see!
Im
Working on my transactional
Mail system this week will be s good way to test it in real live example and see if anything additional comes up

**Comment by Thomascogez** [comment]
Pre-release available on npm under the tag 1.2.0-0

I need to take some time to update documentation and examples, you can access full release by the end of the week

**Comment by Thomascogez** [comment]
This feature has been merged to master and published to npm has version 1.2.0.

I'm closing this issue, thanks for this request hope it will fit your needs 😉

**Comment by Jarrodsz** [comment]
Thank you!

**Comment by Thomascogez** [comment]
Hey, thanks for the report !

If you have time can you make a minimal reproduction repo like that I reproduce this behavior more easily

I will take a look a this by the week-end

Ps: can you open a dedicate issue for this ?

**Comment by Thomascogez** [comment]
What error did you get ?  When using mj-section ?

**Comment by Thomascogez** [comment]
Inside the automated tests, i'm using template where the filename is containing dash.
Can you include more info about the context of the error (eg: plugin option, folder structure , ...)

**Comment by Thomascogez** [comment]
@Jarrodsz any news ?

**Comment by Thomascogez** [comment]
No problem, hope you doing fine.

I will do further investigation to see if i can reproduce this
