### ISSUE TITLE
Incorrect Import Path in Usage examples for nodemailerMjmlPlugin

### ISSUE THREAD

**Issue by adarsht0001** [Thomascogez/nodemailer-mjml#309]
In the usage examples the import for nodemailerMjmlPlugin is from "../src/index".

![image](https://github.com/user-attachments/assets/af2c53f7-f4d5-489a-84d6-de15d2cca4aa)

Suggested fix:

`import { nodemailerMjmlPlugin } from "nodemailer-mjml";`

**Comment by Thomascogez** [comment]
Hello, it was first intended to make examples working locally, but I assume it can be misleading.

Would you like to open a PR for this ? I think it can also be interesting to also include a `package.json` and a minimal `tsconfig.json` inside the example folder ?

**Comment by adarsht0001** [comment]
Hello, 
Thank you for the response! Just to clarify, my concern was actually regarding the README file, not the examples folder. The import path in the examples code block in the  README , which might be confusing for users. I'd be happy to open a PR to update this, along with adding a package.json and a minimal tsconfig.json inside the example folder for additional clarity.
