### ISSUE TITLE
plain text version?

### ISSUE THREAD

**Issue by Jarrodsz** [Thomascogez/nodemailer-mjml#43]
**Is your feature request related to a problem? Please describe.**
Wonder if its possible to also render plain text emails with nodemailer mjml

**Describe the solution you'd like**
Have a plaintext version of the mails beside the html generated version.

**Comment by Thomascogez** [comment]
Hello ! You could use this I think https://www.npmjs.com/package/nodemailer-html-to-text.
`nodemailer-mjml` plugin does not support this feature out of the box

**Comment by Thomascogez** [comment]
I will close this for now, keep free to reopen it if you have any more questions
