### ISSUE TITLE
html doesn't get rendered in content

### ISSUE THREAD

**Issue by AEWebdesign** [Thomascogez/nodemailer-mjml#48]
html inside the content doesn't get rendered:

![image](https://user-images.githubusercontent.com/55782923/221360985-30e9ec33-e833-4d35-967e-0a5077d12310.png)

**Comment by AEWebdesign** [comment]
found a solution: instead of using {{ text }}, you can use {{{ text }}}

https://stackoverflow.com/questions/22910428/mustache-globally-disable-html-escaping

**Comment by Thomascogez** [comment]
Hey! Glad you found a solution, I will add this to a FAQ section in the README 👍
